package qp.parser;


//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Apr 05 17:35:17 SRET 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ORDERBY = 20;
  public static final int WHERE = 17;
  public static final int FROM = 16;
  public static final int AND = 13;
  public static final int GROUPBY = 18;
  public static final int DESC = 22;
  public static final int SELECT = 15;
  public static final int OR = 14;
  public static final int EQUAL = 11;
  public static final int SEMI = 4;
  public static final int NOTEQUAL = 12;
  public static final int LTOE = 9;
  public static final int STAR = 6;
  public static final int ID = 2;
  public static final int GTOE = 10;
  public static final int COMMA = 3;
  public static final int LESSTHAN = 7;
  public static final int EOF = 0;
  public static final int STRINGLIT = 23;
  public static final int DISTINCT = 19;
  public static final int error = 1;
  public static final int DOT = 5;
  public static final int ASC = 21;
  public static final int GREATERTHAN = 8;
}

